version: 0.0
os: linux
files:
  - source: /calculator.jar
    destination: /home/ubuntu/calculator/

hooks:
  AfterInstall:
    - location: resources/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: resources/start.sh
      timeout: 300
      runas: ubuntu
